Se agregan temas de gtk e iconos, se edita el Installer y el script de Theme.sh

diff --git a/Installer b/Installer
--- a/Installer
+++ b/Installer
@@ -6,7 +6,6 @@
 #  ██║██║ ╚████║███████║   ██║   ██║  ██║███████╗███████╗███████╗██║  ██║
 #  ╚═╝╚═╝  ╚═══╝╚══════╝   ╚═╝   ╚═╝  ╚═╝╚══════╝╚══════╝╚══════╝╚═╝  ╚═╝
 
-
 CRE=$(tput setaf 1)
 CYE=$(tput setaf 3)
 CGR=$(tput setaf 2)
@@ -39,7 +38,7 @@ is_installed() {
 
 ########## ---------- Welcome ---------- ##########
 
-printf '%s%sThis script will check if you have the necessary dependencies, and if not, it will install them. Then, it will clone my repository in your HOME directory.\nAfter that, it will create a backup of your files, and then copy the new files to your computer.\n\nMy dotfiles DO NOT modify any of your system configurations.\nYou will be prompted for your root password to install missing dependencies and/or to switch to zsh shell if its not your default.\n\nThis script doesnt have the potential power to break your system, it only copies files from my repository to your HOME directory.%s\n\n' "${BLD}" "${CRE}" "${CNC}"
+printf '%s%sThis script will check if you have the necessary dependencies, and if not, it will install them. Then, it will clone my repository in your HOME directory.\nAfter that, it will create a backup of your files, and then copy the new files to your computer.\n\nMy bspwm_theme DO NOT modify any of your system configurations.\nYou will be prompted for your root password to install missing dependencies and/or to switch to zsh shell if its not your default.\n\nThis script doesnt have the potential power to break your system, it only copies files from my repository to your HOME directory.%s\n\n' "${BLD}" "${CRE}" "${CNC}"
 
 while true; do
     read -rp " Do you wish to continue? [y/N]: " yn
@@ -53,65 +52,102 @@ clear
 
 ########## ---------- Install packages ---------- ##########
 
-logo "Installing needed packages.."
+printf "Installing needed packages.."
 
 dependencias=(alacritty base-devel bat brightnessctl bspwm dunst eza feh gvfs-mtp firefox git imagemagick jq \
-			        jgmenu libwebp maim mpc mpd neovim ncmpcpp npm pamixer pacman-contrib \
-			        papirus-icon-theme picom playerctl polybar polkit-gnome python-gobject \
-			        redshift rofi rustup sxhkd tmux ttf-inconsolata ttf-jetbrains-mono ttf-jetbrains-mono-nerd \
-			        ttf-joypixels ttf-terminus-nerd ttf-ubuntu-mono-nerd ueberzug webp-pixbuf-loader xclip xdg-user-dirs \
-			        xdo xdotool xsettingsd xorg-xdpyinfo xorg-xkill xorg-xprop xorg-xrandr xorg-xsetroot \
-			        xorg-xwininfo yazi zsh)
+                jgmenu libwebp maim neovim npm pamixer pacman-contrib \
+                papirus-icon-theme picom playerctl polybar polkit-gnome python-gobject \
+                redshift rofi rustup sxhkd tmux ttf-inconsolata ttf-jetbrains-mono ttf-jetbrains-mono-nerd \
+                ttf-joypixels ttf-terminus-nerd ttf-ubuntu-mono-nerd ueberzug webp-pixbuf-loader xclip xdg-user-dirs \
+                xdo xdotool xsettingsd xorg-xdpyinfo xorg-xkill xorg-xprop xorg-xrandr xorg-xsetroot \
+                xorg-xwininfo yazi zsh)
 
 printf "%s%sChecking for required packages...%s\n\n" "${BLD}" "${CBL}" "${CNC}"
 
-	for paquete in "${dependencias[@]}"; do
-        if ! is_installed "$paquete"; then
-            if sudo pacman -S "$paquete" --noconfirm >/dev/null 2> >(tee -a "$ERROR_LOG"); then
-                printf "%s%s%s %shas been installed successfully.%s\n" "${BLD}" "${CYE}" "$paquete" "${CBL}" "${CNC}"
-            else
-                printf "%s%s%s %shas not been installed correctly. See %sRiceError.log %sfor more details.%s\n" \
-                       "${BLD}" "${CYE}" "$paquete" "${CRE}" "${CBL}" "${CRE}" "${CNC}"
-                log_error "Failed to install package: $paquete"
-            fi
-            sleep 1
+for paquete in "${dependencias[@]}"; do
+    if ! is_installed "$paquete"; then
+        if sudo pacman -S "$paquete" --noconfirm >/dev/null 2> >(tee -a "$ERROR_LOG"); then
+            printf "%s%s%s %shas been installed successfully.%s\n" "${BLD}" "${CYE}" "$paquete" "${CBL}" "${CNC}"
         else
-            printf '%s%s%s %sis already installed on your system!%s\n' "${BLD}" "${CYE}" "$paquete" "${CGR}" "${CNC}"
-            sleep 1
+            printf "%s%s%s %shas not been installed correctly. See %sRiceError.log %sfor more details.%s\n" \
+                   "${BLD}" "${CYE}" "$paquete" "${CRE}" "${CBL}" "${CRE}" "${CNC}"
+            log_error "Failed to install package: $paquete"
         fi
-    done
+        sleep 1
+    else
+        printf '%s%s%s %sis already installed on your system!%s\n' "${BLD}" "${CYE}" "$paquete" "${CGR}" "${CNC}"
+        sleep 1
+    fi
+done
 sleep 3
 clear
 
 ########## ---------- Preparing Folders ---------- ##########
 
-# Verifies if the archive user-dirs.dirs doesn't exist in ~/.config
 if [ ! -e "$HOME/.config/user-dirs.dirs" ]; then
     xdg-user-dirs-update
 fi
 
 ########## ---------- Cloning the Rice! ---------- ##########
 
-logo "Downloading dotfiles"
+printf "Downloading bspwm_theme"
 
 repo_url="https://github.com/YakitoSX/bspwm_theme"
 repo_dir="$HOME/bspwm_theme"
 
-# Verifies if the folder of the repository exists, and if it does, deletes it
 if [ -d "$repo_dir" ]; then
-    printf "Removing existing dotfiles repository\n"
+    printf "Removing existing bspwm_theme repository\n"
     rm -rf "$repo_dir"
 fi
 
-# Clone the repository
 printf "Cloning bspwm_theme from %s\n" "$repo_url"
 git clone --depth=1 "$repo_url" "$repo_dir"
 sleep 3
 clear
 
+########## ---------- Moving Themes ---------- ##########
+
+# La carpeta 'themes' ya se descargó, vamos a mover los temas
+
+printf "Moving themes"
+themes_dir="$repo_dir/themes"
+if [ -d "$themes_dir" ]; then
+    echo "Found 'themes' directory, moving themes to appropriate locations..."
+    
+    # Mover los temas GTK que están dentro de 'GTK_THEME'
+    if [ -d "$themes_dir/GTK_THEME" ]; then
+        echo "Moving GTK themes..."
+        for theme in "$themes_dir/GTK_THEME"/*; do
+            if [ -d "$theme" ]; then
+                mv "$theme" "$HOME/.themes/"
+                echo "Moved GTK theme: $(basename "$theme")"
+            fi
+        done
+    else
+        echo "No GTK themes found in the 'GTK_THEME' directory."
+    fi
+    
+    # Mover los temas de cursor que están dentro de 'CURSOR_THEME'
+    if [ -d "$themes_dir/CURSOR_THEME" ]; then
+        echo "Moving Cursor themes..."
+        for theme in "$themes_dir/CURSOR_THEME"/*; do
+            if [ -d "$theme" ]; then
+                mv "$theme" "$HOME/.icons/"
+                echo "Moved Cursor theme: $(basename "$theme")"
+            fi
+        done
+    else
+        echo "No Cursor themes found in the 'CURSOR_THEME' directory."
+    fi
+else
+    echo "No 'themes' directory found in the repository."
+fi
+sleep 3
+clear
+
 ########## ---------- Copy the Rice! ---------- ##########
 
-logo "Installing bspwm_theme.."
+printf "Installing bspwm_theme.."
 printf "Copying files to respective directories..\n"
 
 [ ! -d ~/.config ] && mkdir -p ~/.config
@@ -120,28 +156,24 @@ printf "Copying files to respective directories..\n"
 
 for dirs in ~/bspwm_theme/config/*; do
     dir_name=$(basename "$dirs")
-# If the directory is nvim and the user doesn't want to try it, skip this loop
-    if [[ $dir_name == "nvim" && $try_nvim != "y" ]]; then
-        continue
-    fi
     if cp -R "${dirs}" ~/.config/ 2>> RiceError.log; then
-        printf "%s%s%s %sconfiguration installed succesfully%s\n" "${BLD}" "${CYE}" "${dir_name}" "${CGR}" "${CNC}"
+        printf "%s%s%s %sconfiguration installed successfully%s\n" "${BLD}" "${CYE}" "${dir_name}" "${CGR}" "${CNC}"
         sleep 1
     else
-        printf "%s%s%s %sconfiguration failed to been installed, see %sRiceError.log %sfor more details.%s\n" "${BLD}" "${CYE}" "${dir_name}" "${CRE}" "${CBL}" "${CRE}" "${CNC}"
+        printf "%s%s%s %sconfiguration failed to be installed, see %sRiceError.log %sfor more details.%s\n" "${BLD}" "${CYE}" "${dir_name}" "${CRE}" "${CBL}" "${CRE}" "${CNC}"
         sleep 1
     fi
 done
 
 fc-cache -rv >/dev/null 2>&1
 
-printf "\n\n%s%sFiles copied succesfully!!%s\n" "${BLD}" "${CGR}" "${CNC}"
+printf "\n\n%s%sFiles copied successfully!!%s\n" "${BLD}" "${CGR}" "${CNC}"
 sleep 3
 clear
 
 ########## ---------- Installing Paru ---------- ##########
 
-logo "Install Paru"
+printf "Install Paru"
 
 if command -v paru >/dev/null 2>&1; then
     printf "%s%sParu is already installed%s\n" "${BLD}" "${CGR}" "${CNC}"
@@ -152,74 +184,49 @@ else
         git clone https://aur.archlinux.org/paru-bin.git
         cd paru-bin || exit
         makepkg -si --noconfirm
-        } || {
+    } || {
         printf "\n%s%sFailed to install Paru. You may need to install it manually%s\n" "${BLD}" "${CRE}" "${CNC}"
     }
 fi
 sleep 3
 clear
 
-########## ---------- Installing AUR dependencies ---------- ##########
+printf "Installing AUR dependencies"
 
-logo "Installing AUR dependencies."
+# Define an array of AUR dependencies
+aur_dependencies=(tdrop-git xqp rofi-greenclip ttf-maple i3lock-color simple-mtpfs eww-git)
 
-aur_apps=(tdrop-git xqp rofi-greenclip ttf-maple i3lock-color simple-mtpfs eww-git)
-
-printf "%s%sChecking for required packages...%s\n\n" "${BLD}" "${CBL}" "${CNC}"
-for aur_package in "${aur_apps[@]}"; do
-    if ! is_installed "$aur_package"; then
-        if paru -S --skipreview --noconfirm "$aur_package" 2> >(tee -a "$ERROR_LOG"); then
-            printf "%s%s%s %shas been installed succesfully.%s\n" "${BLD}" "${CYE}" "$aur_package" "${CBL}" "${CNC}"
+for aur_package in "${aur_dependencies[@]}"; do
+    if ! paru -Qq "$aur_package" &>/dev/null; then
+        printf "%s%sInstalling %s...%s\n" "${BLD}" "${CYE}" "$aur_package" "${CNC}"
+        if paru -S "$aur_package" --noconfirm >/dev/null 2> >(tee -a "$ERROR_LOG"); then
+            printf "%s%s%s %sinstalled successfully.%s\n" "${BLD}" "${CGR}" "$aur_package" "${CBL}" "${CNC}"
         else
-            printf "%s%s%s %shas not been installed correctly. See %sRiceError.log %sfor more details.%s\n" "${BLD}" "${CYE}" "$aur_package" "${CRE}" "${CBL}" "${CRE}" "${CNC}"
-            log_error "Failed to install package: $aur_package"
+            printf "%s%s%s %sinstallation failed. Check %sRiceError.log %sfor details.%s\n" \
+                   "${BLD}" "${CRE}" "$aur_package" "${CRE}" "${CBL}" "${CRE}" "${CNC}"
+            log_error "Failed to install AUR package: $aur_package"
         fi
-        sleep 1
     else
-        printf '%s%s%s %sis already installed on your system!%s\n' "${BLD}" "${CYE}" "$aur_package" "${CGR}" "${CNC}"
-        sleep 1
+        printf "%s%s%s %sis already installed.%s\n" "${BLD}" "${CGR}" "$aur_package" "${CBL}" "${CNC}"
     fi
+    sleep 1
 done
+
+printf "\n%s%sAll AUR dependencies checked and processed.%s\n" "${BLD}" "${CGR}" "${CNC}"
 sleep 3
 clear
 
-########## ---------- Enabling MPD service ---------- ##########
+########## ---------- Setting up BSPWM and Polybar ---------- ##########
 
-logo "Enabling mpd service"
+printf "Setting up BSPWM and Polybar configuration."
 
-	if systemctl is-enabled --quiet mpd.service; then
-        printf "%s%sDisabling and stopping the global mpd service%s\n" "${BLD}" "${CBL}" "${CNC}"
-
-        if sudo systemctl disable --now mpd.service >/dev/null 2> >(tee -a "$ERROR_LOG"); then
-            sleep 1
-            printf "\n%s[%sOK%s%s]%s Global MPD service disabled successfully\n\n" \
-                   "${BLD}" "${CGR}" "${CNC}" "${BLD}" "${CNC}"
-        else
-            sleep 1
-            printf "%s[%sError%s%s] Please check %sRiceError.log%s for details\n\n" \
-               "${BLD}" "${CRE}" "${CNC}" "${BLD}" "${CYE}" "${CNC}"
-            log_error "Failed to disable global MPD service"
-		fi
-	fi
-
-    printf "%s%sEnabling and starting the user-level mpd service%s\n\n" "${BLD}" "${CBL}" "${CNC}"
-
-    if systemctl --user enable --now mpd.service >/dev/null 2> >(tee -a "$ERROR_LOG"); then
-        sleep 1
-        printf "%s[%sOK%s%s]%s User-level MPD service enabled successfully\n\n" \
-               "${BLD}" "${CGR}" "${CNC}" "${BLD}" "${CNC}"
-    else
-        sleep 1
-        printf "%s[%sError%s%s] Please check %sRiceError.log%s for details\n\n" \
-               "${BLD}" "${CRE}" "${CNC}" "${BLD}" "${CYE}" "${CNC}"
-        log_error "Failed to enable user-level MPD service"
-    fi
-sleep 3
-clear
+# Permissions for bspwm and sxhkd
+chmod +x ~/.config/bspwm/bspwmrc
+chmod +x ~/.config/bspwm/src/config/sxhkdrc
 
 ########## --------- Changing shell to zsh ---------- ##########
 
-logo "Changing default shell to zsh"
+printf "Changing default shell to zsh"
 
 	if [[ $SHELL != "/usr/bin/zsh" ]]; then
         printf "%s%sChanging your shell to zsh...%s\n\n" "${BLD}" "${CYE}" "${CNC}"
@@ -239,7 +246,7 @@ clear
 
 ########## --------- exit ---------- ##########
 
-logo "Installation is compñete"
+printf "Installation is complete"
 
 printf "%sThe installation is complete, you %sneed%s to restart your machine.%s\n\n" "${BLD}" "${CBL}" "${CNC}" "${CNC}"
 
@@ -261,3 +268,14 @@ printf "%sThe installation is complete, you %sneed%s to restart your machine.%s\
 				;;
 		esac
 	done
+
+# Clean up: Remove the cloned repository and the installer script
+echo "Cleaning up temporary files..."
+
+# Eliminar el directorio clonado
+rm -rf "$HOME/bspwm_theme"
+
+# Eliminar el archivo del instalador
+rm -f "$0"  # Esto eliminará el script del instalador
+
+echo "Cleanup completed!"
