Se arreglan modulos

diff --git a/Installer b/Installer
--- a/Installer
+++ b/Installer
@@ -115,16 +115,17 @@ printf "Installing AUR dependencies\n"
 
 # Instalar fuentes con yay
 for aur_package in "${aur_dependencies[@]}"; do
-    if ! pacman -Qi "$aur_package" &>/dev/null; then
-        printf "%s%sInstalling %s...%s\n" "${BLD}" "${CYE}" "$aur_package" "${CNC}"
-        if yay -S --noconfirm "$aur_package" >/dev/null 2> >(tee -a "$ERROR_LOG"); then
-            printf "%s%s%s has been installed successfully.%s\n" "${BLD}" "${CYE}" "$aur_package" "${CNC}"
+    if ! is_installed "$aur_package"; then
+        if yay -S --skipreview --noconfirm "$aur_package" 2> >(tee -a "$ERROR_LOG"); then
+            printf "%s%s%s %shas been installed succesfully.%s\n" "${BLD}" "${CYE}" "$aur_package" "${CBL}" "${CNC}"
         else
-            printf "%s%sError: %s could not be installed. Check %s%s%s for details.%s\n" \
-                   "${BLD}" "${CRE}" "$aur_package" "${CYE}" "$ERROR_LOG" "${CRE}" "${CNC}"
+            printf "%s%s%s %shas not been installed correctly. See %sInstallerError.log %sfor more details.%s\n" "${BLD}" "${CYE}" "$aur_package" "${CRE}" "${CBL}" "${CRE}" "${CNC}"
+            log_error "Failed to install package: $aur_package"
         fi
+        sleep 1
     else
-        printf "%s%s%s is already installed on your system!%s\n" "${BLD}" "${CGR}" "$aur_package" "${CNC}"
+        printf '%s%s%s %sis already installed on your system!%s\n' "${BLD}" "${CYE}" "$aur_package" "${CGR}" "${CNC}"
+        sleep 1
     fi
 done
 
